version: '3.3'

services:

  application:
    image:
      user-applicationlisener-image
    container_name: application-2
    ports:
      - 8080:8080
    depends_on:
      - database
      - redis
      - rabbit
      - application-rest
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/app_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty009"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6380"
      - "RABBIT_HOST=rabbit"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty009
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      redis-filesync
    container_name: redis
    ports:
      - 6380:6380
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  rabbit:
    image:
      rabbitmq
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672

  application-rest:
    image:
      user-application-image
    container_name: application-
    ports:
      - 80:80
    depends_on:
      - database
      - redis
      - rabbit
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/app_db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty009"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6380"
      - "RABBIT_HOST=rabbit"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
volumes:
  pgdata:
    external: true
  redis-volume:
    external: true

